// <auto-generated />
using DAB_Assignment2;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAB_Assignment2.Migrations
{
    [DbContext(typeof(FacilitysContext))]
    [Migration("20221104091937_test2")]
    partial class test2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.10");

            modelBuilder.Entity("DAB_Assignment2.Facilitys", b =>
                {
                    b.Property<string>("PK_FcName")
                        .HasColumnType("TEXT");

                    b.Property<string>("CanBeBookedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClosetAdress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FacilityDecrtiption")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FcType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PK_FcName");

                    b.ToTable("Facilitys");
                });
#pragma warning restore 612, 618
        }
    }
}
